create or replace package body finance_data_exchange

as

begin

  dbms_application_info.set_client_info('finance_data_exchange');
  dbms_session.set_identifier('finance_data_exchange');

  finance_data.exchanges(1).exchange_name := 'New Zealand Stock Exchange';
  finance_data.exchanges(1).exchange_id := 'NZSX';
  finance_data.exchanges(1).timezone := null;
  finance_data.exchanges(2).exchange_name := 'Australian Stock Exchange';
  finance_data.exchanges(2).exchange_id := 'ASX';
  finance_data.exchanges(2).timezone := null;
  finance_data.exchanges(3).exchange_name := 'Tokyo Stock Exchange';
  finance_data.exchanges(3).exchange_id := 'TSE';
  finance_data.exchanges(3).timezone := null;
  finance_data.exchanges(4).exchange_name := 'Korea Stock Exchange';
  finance_data.exchanges(4).exchange_id := 'KRX';
  finance_data.exchanges(4).timezone := null;
  finance_data.exchanges(5).exchange_name := 'Bursa Malaysia';
  finance_data.exchanges(5).exchange_id := 'MYX';
  finance_data.exchanges(5).timezone := null;
  finance_data.exchanges(6).exchange_name := 'Singapore Exchange';
  finance_data.exchanges(6).exchange_id := 'SGX';
  finance_data.exchanges(6).timezone := null;
  finance_data.exchanges(7).exchange_name := 'Taiwan Stock Exchange';
  finance_data.exchanges(7).exchange_id := 'TWSE';
  finance_data.exchanges(7).timezone := null;
  finance_data.exchanges(8).exchange_name := 'Hong Kong Stock Exchange';
  finance_data.exchanges(8).exchange_id := 'HKEX';
  finance_data.exchanges(8).timezone := null;
  finance_data.exchanges(9).exchange_name := 'Shenzhen Stock Exchange';
  finance_data.exchanges(9).exchange_id := 'SZSE';
  finance_data.exchanges(9).timezone := null;
  finance_data.exchanges(10).exchange_name := 'Philippine Stock Exchange';
  finance_data.exchanges(10).exchange_id := 'PSE';
  finance_data.exchanges(10).timezone := null;
  finance_data.exchanges(11).exchange_name := 'Indonesia Stock Exchange';
  finance_data.exchanges(11).exchange_id := 'IDX';
  finance_data.exchanges(11).timezone := null;
  finance_data.exchanges(12).exchange_name := 'Hochiminh Stock Exchange';
  finance_data.exchanges(12).exchange_id := 'HOSE';
  finance_data.exchanges(12).timezone := null;
  finance_data.exchanges(13).exchange_name := 'Stock Exchange of Thailand';
  finance_data.exchanges(13).exchange_id := 'SET';
  finance_data.exchanges(13).timezone := null;
  finance_data.exchanges(14).exchange_name := 'National Stock Exchange of India';
  finance_data.exchanges(14).exchange_id := 'NSE';
  finance_data.exchanges(14).timezone := null;
  finance_data.exchanges(15).exchange_name := 'Moscow Exchange';
  finance_data.exchanges(15).exchange_id := 'MOEX';
  finance_data.exchanges(15).timezone := null;
  finance_data.exchanges(16).exchange_name := 'Helsinki Stock Exchange';
  finance_data.exchanges(16).exchange_id := 'OMX';
  finance_data.exchanges(16).timezone := null;
  finance_data.exchanges(17).exchange_name := 'Frankfurt Stock Exchange';
  finance_data.exchanges(17).exchange_id := 'FSX';
  finance_data.exchanges(17).timezone := null;
  finance_data.exchanges(18).exchange_name := 'Eurex Exchange';
  finance_data.exchanges(18).exchange_id := 'EUREX';
  finance_data.exchanges(18).timezone := null;
  finance_data.exchanges(19).exchange_name := 'Swiss Stock Exchange';
  finance_data.exchanges(19).exchange_id := 'SIX';
  finance_data.exchanges(19).timezone := null;
  finance_data.exchanges(20).exchange_name := 'Vienna Stock Exchange';
  finance_data.exchanges(20).exchange_id := 'VSE';
  finance_data.exchanges(20).timezone := null;
  finance_data.exchanges(21).exchange_name := 'Euronext Paris';
  finance_data.exchanges(21).exchange_id := 'EPA';
  finance_data.exchanges(21).timezone := null;
  finance_data.exchanges(21).exchange_name := 'Spanish Stock Exchange';
  finance_data.exchanges(21).exchange_id := 'BME';
  finance_data.exchanges(21).timezone := null;
  finance_data.exchanges(22).exchange_name := 'Milan Stock Exchange';
  finance_data.exchanges(22).exchange_id := 'MTA';
  finance_data.exchanges(22).timezone := null;
  finance_data.exchanges(23).exchange_name := 'Euronext Amsterdam';
  finance_data.exchanges(23).exchange_id := 'AMS';
  finance_data.exchanges(23).timezone := null;
  finance_data.exchanges(24).exchange_name := 'Stockholm Stock Exchange';
  finance_data.exchanges(24).exchange_id := 'STO';
  finance_data.exchanges(24).timezone := null;
  finance_data.exchanges(25).exchange_name := 'Oslo Stock Exchange';
  finance_data.exchanges(25).exchange_id := 'OSE';
  finance_data.exchanges(25).timezone := null;
  finance_data.exchanges(26).exchange_name := 'Copenhagen Stock Exchange';
  finance_data.exchanges(26).exchange_id := 'CSE';
  finance_data.exchanges(26).timezone := null;
  finance_data.exchanges(27).exchange_name := 'London Stock Exchange';
  finance_data.exchanges(27).exchange_id := 'LSE';
  finance_data.exchanges(27).timezone := null;
  finance_data.exchanges(28).exchange_name := 'Irish Stock Exchange';
  finance_data.exchanges(28).exchange_id := 'ISE';
  finance_data.exchanges(28).timezone := null;
  finance_data.exchanges(29).exchange_name := 'BMV and F Bovespa Stock Exchange';
  finance_data.exchanges(29).exchange_id := 'SAO';
  finance_data.exchanges(29).timezone := null;
  finance_data.exchanges(30).exchange_name := 'Buenos Aires Stock Exchange';
  finance_data.exchanges(30).exchange_id := 'BCBA';
  finance_data.exchanges(30).timezone := null;
  finance_data.exchanges(31).exchange_name := 'New York Stock Exchange';
  finance_data.exchanges(31).exchange_id := 'NYSE';
  finance_data.exchanges(31).timezone := null;
  finance_data.exchanges(32).exchange_name := 'New York Stock Exchange ARCA';
  finance_data.exchanges(32).exchange_id := 'NYSEArca';
  finance_data.exchanges(32).timezone := null;
  finance_data.exchanges(33).exchange_name := 'Nasdaq';
  finance_data.exchanges(33).exchange_id := 'NASDAQ';
  finance_data.exchanges(33).timezone := null;

end finance_data_exchange;
/
