create or replace package body finance_data_account

as

begin

  dbms_application_info.set_client_info('finance_data_account');
  dbms_session.set_identifier('finance_data_account');

  -- Bank account types.
  finance_data.account_types(1).type_name := 'Current Account';
  finance_data.account_types(1).transaction_types := 'ATM,Charge,Check,Deposit,Online,Transfer,Withdrawal';
  finance_data.account_types(1).average_balance := 2500;
  finance_data.account_types(2).type_name := 'Investment Account';
  finance_data.account_types(2).transaction_types := 'Buy,Buy to Close,Buy to Open,Dividend,Cap. Distribution,Cap. Gains long,Cap. Gains Short,Interest,Move,Sell,Sell to Close,Split';
  finance_data.account_types(2).average_balance := 50000;
  finance_data.account_types(3).type_name := 'Savings Account';
  finance_data.account_types(3).transaction_types := 'Deposit,Withdrawal,Interest';
  finance_data.account_types(3).average_balance := 4000;

  -- Bank account formats.
  finance_data.country_bankaccounts('AL').iban_length := 28;
  finance_data.country_bankaccounts('AL').bban_format := 'nnnnnnnxcccccccccccccccc';
  finance_data.country_bankaccounts('AL').bban_min := 28;
  finance_data.country_bankaccounts('AL').bban_max := 28;
  finance_data.country_bankaccounts('AD').iban_length := 24;
  finance_data.country_bankaccounts('AD').bban_format := 'nnnnnnnncccccccccccc';
  finance_data.country_bankaccounts('AD').bban_min := 24;
  finance_data.country_bankaccounts('AD').bban_max := 24;
  finance_data.country_bankaccounts('AT').iban_length := 20;
  finance_data.country_bankaccounts('AT').bban_format := 'nnnnnnnnnnnnnnnn';
  finance_data.country_bankaccounts('AT').bban_min := 20;
  finance_data.country_bankaccounts('AT').bban_max := 20;
  finance_data.country_bankaccounts('AZ').iban_length := 28;
  finance_data.country_bankaccounts('AZ').bban_format := 'ccccnnnnnnnnnnnnnnnnnnnn';
  finance_data.country_bankaccounts('AZ').bban_min := 28;
  finance_data.country_bankaccounts('AZ').bban_max := 28;
  finance_data.country_bankaccounts('BH').iban_length := 22;
  finance_data.country_bankaccounts('BH').bban_format := 'aaaacccccccccccccc';
  finance_data.country_bankaccounts('BH').bban_min := 22;
  finance_data.country_bankaccounts('BH').bban_max := 22;
  finance_data.country_bankaccounts('BE').iban_length := 16;
  finance_data.country_bankaccounts('BE').bban_format := 'nnnnnnnnnnnn';
  finance_data.country_bankaccounts('BE').bban_min := 16;
  finance_data.country_bankaccounts('BE').bban_max := 16;
  finance_data.country_bankaccounts('BA').iban_length := 20;
  finance_data.country_bankaccounts('BA').bban_format := 'nnnnnnnnnnnnnnnn';
  finance_data.country_bankaccounts('BA').bban_min := 20;
  finance_data.country_bankaccounts('BA').bban_max := 20;
  finance_data.country_bankaccounts('BR').iban_length := 29;
  finance_data.country_bankaccounts('BR').bban_format := 'nnnnnnnnnnnnnnnnnnnnnnnac';
  finance_data.country_bankaccounts('BR').bban_min := 29;
  finance_data.country_bankaccounts('BR').bban_max := 29;
  finance_data.country_bankaccounts('BG').iban_length := 22;
  finance_data.country_bankaccounts('BG').bban_format := 'aaaannnnnncccccccc';
  finance_data.country_bankaccounts('BG').bban_min := 22;
  finance_data.country_bankaccounts('BG').bban_max := 22;
  finance_data.country_bankaccounts('CR').iban_length := 22;
  finance_data.country_bankaccounts('CR').bban_format := 'nnnnnnnnnnnnnnnnnn';
  finance_data.country_bankaccounts('CR').bban_min := 22;
  finance_data.country_bankaccounts('CR').bban_max := 22;
  finance_data.country_bankaccounts('HR').iban_length := 21;
  finance_data.country_bankaccounts('HR').bban_format := 'nnnnnnnnnnnnnnnnn';
  finance_data.country_bankaccounts('HR').bban_min := 21;
  finance_data.country_bankaccounts('HR').bban_max := 21;
  finance_data.country_bankaccounts('CY').iban_length := 28;
  finance_data.country_bankaccounts('CY').bban_format := 'nnnnnnnncccccccccccccccc';
  finance_data.country_bankaccounts('CY').bban_min := 28;
  finance_data.country_bankaccounts('CY').bban_max := 28;
  finance_data.country_bankaccounts('CZ').iban_length := 24;
  finance_data.country_bankaccounts('CZ').bban_format := 'nnnnnnnnnnnnnnnnnnnn';
  finance_data.country_bankaccounts('CZ').bban_min := 24;
  finance_data.country_bankaccounts('CZ').bban_max := 24;
  finance_data.country_bankaccounts('DK').iban_length := 18;
  finance_data.country_bankaccounts('DK').bban_format := 'nnnnnnnnnnnnnn';
  finance_data.country_bankaccounts('DK').bban_min := 18;
  finance_data.country_bankaccounts('DK').bban_max := 18;
  finance_data.country_bankaccounts('DO').iban_length := 28;
  finance_data.country_bankaccounts('DO').bban_format := 'aaaannnnnnnnnnnnnnnnnnnn';
  finance_data.country_bankaccounts('DO').bban_min := 28;
  finance_data.country_bankaccounts('DO').bban_max := 28;
  finance_data.country_bankaccounts('TL').iban_length := 23;
  finance_data.country_bankaccounts('TL').bban_format := 'nnnnnnnnnnnnnnnnnnn';
  finance_data.country_bankaccounts('TL').bban_min := 23;
  finance_data.country_bankaccounts('TL').bban_max := 23;
  finance_data.country_bankaccounts('EE').iban_length := 20;
  finance_data.country_bankaccounts('EE').bban_format := 'nnnnnnnnnnnnnnnn';
  finance_data.country_bankaccounts('EE').bban_min := 20;
  finance_data.country_bankaccounts('EE').bban_max := 20;
  finance_data.country_bankaccounts('FO').iban_length := 18;
  finance_data.country_bankaccounts('FO').bban_format := 'nnnnnnnnnnnnnn';
  finance_data.country_bankaccounts('FO').bban_min := 18;
  finance_data.country_bankaccounts('FO').bban_max := 18;
  finance_data.country_bankaccounts('FI').iban_length := 18;
  finance_data.country_bankaccounts('FI').bban_format := 'nnnnnnnnnnnnnn';
  finance_data.country_bankaccounts('FI').bban_min := 18;
  finance_data.country_bankaccounts('FI').bban_max := 18;
  finance_data.country_bankaccounts('FR').iban_length := 27;
  finance_data.country_bankaccounts('FR').bban_format := 'nnnnnnnnnncccccccccccnn';
  finance_data.country_bankaccounts('FR').bban_min := 27;
  finance_data.country_bankaccounts('FR').bban_max := 27;
  finance_data.country_bankaccounts('GE').iban_length := 22;
  finance_data.country_bankaccounts('GE').bban_format := 'ccnnnnnnnnnnnnnnnn';
  finance_data.country_bankaccounts('GE').bban_min := 22;
  finance_data.country_bankaccounts('GE').bban_max := 22;
  finance_data.country_bankaccounts('DE').iban_length := 22;
  finance_data.country_bankaccounts('DE').bban_format := 'nnnnnnnnnnnnnnnnnn';
  finance_data.country_bankaccounts('DE').bban_min := 22;
  finance_data.country_bankaccounts('DE').bban_max := 22;
  finance_data.country_bankaccounts('GI').iban_length := 23;
  finance_data.country_bankaccounts('GI').bban_format := 'aaaaccccccccccccccc';
  finance_data.country_bankaccounts('GI').bban_min := 23;
  finance_data.country_bankaccounts('GI').bban_max := 23;
  finance_data.country_bankaccounts('GR').iban_length := 27;
  finance_data.country_bankaccounts('GR').bban_format := 'nnnnnnncccccccccccccccc';
  finance_data.country_bankaccounts('GR').bban_min := 27;
  finance_data.country_bankaccounts('GR').bban_max := 27;
  finance_data.country_bankaccounts('GL').iban_length := 18;
  finance_data.country_bankaccounts('GL').bban_format := 'nnnnnnnnnnnnnn';
  finance_data.country_bankaccounts('GL').bban_min := 18;
  finance_data.country_bankaccounts('GL').bban_max := 18;
  finance_data.country_bankaccounts('GT').iban_length := 28;
  finance_data.country_bankaccounts('GT').bban_format := 'cccccccccccccccccccccccc';
  finance_data.country_bankaccounts('GT').bban_min := 28;
  finance_data.country_bankaccounts('GT').bban_max := 28;
  finance_data.country_bankaccounts('HU').iban_length := 28;
  finance_data.country_bankaccounts('HU').bban_format := 'nnnnnnnnnnnnnnnnnnnnnnnn';
  finance_data.country_bankaccounts('HU').bban_min := 28;
  finance_data.country_bankaccounts('HU').bban_max := 28;
  finance_data.country_bankaccounts('IS').iban_length := 26;
  finance_data.country_bankaccounts('IS').bban_format := 'nnnnnnnnnnnnnnnnnnnnnn';
  finance_data.country_bankaccounts('IS').bban_min := 26;
  finance_data.country_bankaccounts('IS').bban_max := 26;
  finance_data.country_bankaccounts('IE').iban_length := 22;
  finance_data.country_bankaccounts('IE').bban_format := 'ccccnnnnnnnnnnnnnn';
  finance_data.country_bankaccounts('IE').bban_min := 22;
  finance_data.country_bankaccounts('IE').bban_max := 22;
  finance_data.country_bankaccounts('IL').iban_length := 23;
  finance_data.country_bankaccounts('IL').bban_format := 'nnnnnnnnnnnnnnnnnnn';
  finance_data.country_bankaccounts('IL').bban_min := 23;
  finance_data.country_bankaccounts('IL').bban_max := 23;
  finance_data.country_bankaccounts('IT').iban_length := 27;
  finance_data.country_bankaccounts('IT').bban_format := 'annnnnnnnnncccccccccccc';
  finance_data.country_bankaccounts('IT').bban_min := 27;
  finance_data.country_bankaccounts('IT').bban_max := 27;

end finance_data_account;
/
