create or replace package body location_data_cn

as

begin

  dbms_application_info.set_client_info('location_data_cn');
  dbms_session.set_identifier('location_data_cn');

  -- Init arrays
  location_data.states('CN') := location_data.state_list(null);
  location_data.states('CN').extend(34);
  location_data.road_endings('CN') := location_data.road_list(null);
  location_data.road_endings('CN').extend(3);
  location_data.second_addresses('CN') := location_data.address2_list(null);
  location_data.second_addresses('CN').extend(6);

  -- Road names
  location_data.road_endings('CN')(1).road_name_full := '路';
  location_data.road_endings('CN')(1).road_name_short := '路';
  location_data.road_endings('CN')(1).road_name_ext := 'Y';
  location_data.road_endings('CN')(2).road_name_full := '街';
  location_data.road_endings('CN')(2).road_name_short := '街';
  location_data.road_endings('CN')(2).road_name_ext := 'Y';
  location_data.road_endings('CN')(3).road_name_full := '道';
  location_data.road_endings('CN')(3).road_name_short := '道';
  location_data.road_endings('CN')(3).road_name_ext := 'Y';

  -- Regions/Provinces
  location_data.states('CN')(1).state_name := '北京市';
  location_data.states('CN')(1).state_short := '京';
  location_data.states('CN')(1).state_capital := '北京市';
  location_data.states('CN')(1).cities := '景山街道,东华门街道,交道口街道,安定门街道,金融街街道,西长安街街道,什刹海街道,和平街街道,小关街道,酒仙桥街道,团结湖街道,大红门街道,八宝山街道,苹果园街道,宋庄镇,台湖镇';
  location_data.states('CN')(2).state_name := '天津市';
  location_data.states('CN')(2).state_short := '津';
  location_data.states('CN')(2).state_capital := '天津';
  location_data.states('CN')(2).cities := '小白楼街道,体育馆街道,南营门社区街道,大营门街道,友谊路街道,陈塘庄街道,新立街道,军粮城街道,天穆镇,西堤头镇,海滨街道,大田镇,小王庄镇';
  location_data.states('CN')(3).state_name := '河北省';
  location_data.states('CN')(3).state_short := '冀';
  location_data.states('CN')(3).state_capital := '石家庄市';
  location_data.states('CN')(3).cities := '	遵化市,迁安市,昌黎县,北戴河区,邯郸,武安市,南宫市,沙河市,定州市,涿州市,安国市,高碑店市,张家口市,下花园区,平泉市,西大街街道,新华路街道,泊头市,任丘市,黄骅市,河间市,霸州市,三河市,深州市';
  location_data.states('CN')(4).state_name := '山西省';
  location_data.states('CN')(4).state_short := '晋';
  location_data.states('CN')(4).state_capital := '太原市';
  location_data.states('CN')(4).cities := '古交市,万柏林区,迎泽区,大同市,阳高县,广灵县,阳泉市,城区,郊区,城区,潞城市,平顺县,晋城市,高平市,沁水县,朔州市,平鲁区,介休市,太谷县,临汾市';
  location_data.states('CN')(5).state_name := '內蒙古自治区';
  location_data.states('CN')(5).state_short := '內蒙古(蒙)';
  location_data.states('CN')(5).state_capital := '呼和浩特';
  location_data.states('CN')(5).cities := '回民区,玉泉区,托克托县,和林格尔县,清水河县';
  location_data.states('CN')(6).state_name := '辽宁省';
  location_data.states('CN')(6).state_short := '辽';
  location_data.states('CN')(6).state_capital := '沈阳市';
  location_data.states('CN')(6).cities := '大连市,鞍山市,辽阳市,抚顺市,丹东市,锦州市,营口市';
  location_data.states('CN')(7).state_name := '吉林省';
  location_data.states('CN')(7).state_short := '吉';
  location_data.states('CN')(7).state_capital := '長春市';
  location_data.states('CN')(7).cities := '长春市,吉林市,四平市,辽源市,通化市,白山市,松原市,白城市,延边朝鲜族自治州';
  location_data.states('CN')(8).state_name := '黑龙江省';
  location_data.states('CN')(8).state_short := '黑';
  location_data.states('CN')(8).state_capital := '哈尔滨市';
  location_data.states('CN')(8).cities := '齐齐哈尔市,牡丹江市,佳木斯市,大庆市,鸡西市,双鸭山市,鹤岗市,七台河市,伊春市,黑河市';
  location_data.states('CN')(9).state_name := '上海市';
  location_data.states('CN')(9).state_short := '沪';
  location_data.states('CN')(9).state_capital := '上海市';
  location_data.states('CN')(9).cities := '半淞园路街道,南京东路街道,长桥街道,湖南路街道,宝山路街道,共和新路街道,高桥镇,合庆镇,三林镇,七宝镇,虹桥镇';
  location_data.states('CN')(10).state_name := '江苏省';
  location_data.states('CN')(10).state_short := '苏';
  location_data.states('CN')(10).state_capital := '南京市';
  location_data.states('CN')(10).cities := '苏州市,无锡市,徐州市,常州市,扬州市,连云港市,淮安市,镇江市,南通市,泰州市,宿迁市,姜堰区';
  location_data.states('CN')(11).state_name := '浙江省';
  location_data.states('CN')(11).state_short := '浙';
  location_data.states('CN')(11).state_capital := '杭州市';
  location_data.states('CN')(11).cities := '杭州市,宁波市,温州市,嘉兴市,湖州市,绍兴市,金华市,衢州市,舟山市,台州市,丽水市';
  location_data.states('CN')(12).state_name := '安徽省';
  location_data.states('CN')(12).state_short := '皖';
  location_data.states('CN')(12).state_capital := '合肥市';
  location_data.states('CN')(12).cities := '芜湖,安庆市,黄山市,铜陵市,马鞍山市,淮南市,蚌埠市,亳州市,宿州市,六安市';
  location_data.states('CN')(13).state_name := '福建省';
  location_data.states('CN')(13).state_short := '闽';
  location_data.states('CN')(13).state_capital := '福州市';
  location_data.states('CN')(13).cities := '福州市,厦门市,莆田市,三明市,泉州市,漳州市,南平市,龙岩市,宁德市';
  location_data.states('CN')(14).state_name := '江西省';
  location_data.states('CN')(14).state_short := '赣';
  location_data.states('CN')(14).state_capital := '南昌市';
  location_data.states('CN')(14).cities := '南昌市,景德镇市,萍乡市,新余市,鹰潭市,赣州市,吉安市,宜春市,抚州市,上饶市';
  location_data.states('CN')(15).state_name := '山东省';
  location_data.states('CN')(15).state_short := '鲁';
  location_data.states('CN')(15).state_capital := '济南市';
  location_data.states('CN')(15).cities := '青岛市,淄博市,枣庄市,东营市,烟台市,潍坊市,济宁市,泰安市,威海市,日照市,莱芜市,临沂市,德州市,聊城市,滨州市,菏泽市';
  location_data.states('CN')(16).state_name := '河南省';
  location_data.states('CN')(16).state_short := '豫';
  location_data.states('CN')(16).state_capital := '郑州市';
  location_data.states('CN')(16).cities := '开封市,洛阳市,平顶山市,安阳市,鹤壁市,新乡市,焦作市,濮阳市,许昌市,漯河市,三门峡市,南阳市,商丘市,周口市';
  location_data.states('CN')(17).state_name := '湖北省';
  location_data.states('CN')(17).state_short := '鄂';
  location_data.states('CN')(17).state_capital := '武汉市';
  location_data.states('CN')(17).cities := '武汉市,黄石市,十堰市,宜昌市,襄阳市,鄂州市,荆门市,孝感市,荆州市,黄冈市,咸宁市,随州市';
  location_data.states('CN')(18).state_name := '湖南省';
  location_data.states('CN')(18).state_short := '湘';
  location_data.states('CN')(18).state_capital := '长沙市';
  location_data.states('CN')(18).cities := '株洲市,湘潭市,衡阳市,邵阳市,岳阳市,常德市,张家界市,益阳市,郴州市,永州市,怀化市,娄底市';
  location_data.states('CN')(19).state_name := '广东省';
  location_data.states('CN')(19).state_short := '粤';
  location_data.states('CN')(19).state_capital := '广州市';
  location_data.states('CN')(19).cities := '韶关市,深圳市,珠海市,汕头市,佛山市,江门市,湛江市,茂名市,肇庆市,惠州市,梅州市,汕尾市,河源市,阳江市,清远市,东莞市,揭阳市';
  location_data.states('CN')(20).state_name := '广西壮族自治区';
  location_data.states('CN')(20).state_short := '桂';
  location_data.states('CN')(20).state_capital := '南宁市';
  location_data.states('CN')(20).cities := '南宁市,柳州市,桂林市,梧州市,北海市,防城港市,钦州市,贵港市,玉林市,百色市,贺州市,河池市,来宾市';
  location_data.states('CN')(21).state_name := '海南省';
  location_data.states('CN')(21).state_short := '琼';
  location_data.states('CN')(21).state_capital := '海口市';
  location_data.states('CN')(21).cities := '三亚市,三沙市,儋州市,五指山市,琼海市,文昌市,万宁市,东方市,定安县,屯昌县,临高县';
  location_data.states('CN')(22).state_name := '重庆市';
  location_data.states('CN')(22).state_short := '渝';
  location_data.states('CN')(22).state_capital := '重庆市';
  location_data.states('CN')(22).cities := '万州区,涪陵区,渝中区,大渡口区,沙坪坝区,九龙坡区,南岸区,北碚区,綦江区,大足区,渝北区,巴南区,黔江区,长寿区,江津区,合川区';
  location_data.states('CN')(23).state_name := '四川省';
  location_data.states('CN')(23).state_short := '川(蜀)';
  location_data.states('CN')(23).state_capital := '成都市';
  location_data.states('CN')(23).cities := '自贡市,攀枝花市,泸州市,德阳市,绵阳市,广元市,遂宁市,内江市,乐山市,南充市,眉山市,宜宾市,广安市,达州市';
  location_data.states('CN')(24).state_name := '贵州省';
  location_data.states('CN')(24).state_short := '贵(黔)';
  location_data.states('CN')(24).state_capital := '贵阳市';
  location_data.states('CN')(24).cities := '贵阳市,六盘水市,遵义市,安顺市,毕节市,铜仁市';
  location_data.states('CN')(25).state_name := '云南省';
  location_data.states('CN')(25).state_short := '云';
  location_data.states('CN')(25).state_capital := '昆明市';
  location_data.states('CN')(25).cities := '曲靖市,玉溪市,保山市,昭通市,丽江市,普洱市,临沧市';
  location_data.states('CN')(26).state_name := '西藏自治区';
  location_data.states('CN')(26).state_short := '藏';
  location_data.states('CN')(26).state_capital := '拉萨市';
  location_data.states('CN')(26).cities := '日喀则市,昌都市,林芝市,山南市,那曲地区,阿里地区';
  location_data.states('CN')(27).state_name := '陕西省';
  location_data.states('CN')(27).state_short := '陕';
  location_data.states('CN')(27).state_capital := '西安市';
  location_data.states('CN')(27).cities := '铜川市,宝鸡市,咸阳市,渭南市,延安市,汉中市,榆林市,安康市,商洛市';
  location_data.states('CN')(28).state_name := '甘肃省';
  location_data.states('CN')(28).state_short := '甘';
  location_data.states('CN')(28).state_capital := '兰州市';
  location_data.states('CN')(28).cities := '嘉峪关市,金昌市,白银市,天水市,武威市,张掖市,平凉市,酒泉市,庆阳市,定西市,陇南市';
  location_data.states('CN')(29).state_name := '青海省';
  location_data.states('CN')(29).state_short := '青';
  location_data.states('CN')(29).state_capital := '西宁市';
  location_data.states('CN')(29).cities := '海东市,海北藏族自治州,黄南藏族自治州,海南藏族自治州,果洛藏族自治州';
  location_data.states('CN')(30).state_name := '宁夏回族自治区';
  location_data.states('CN')(30).state_short := '宁';
  location_data.states('CN')(30).state_capital := '银川市';
  location_data.states('CN')(30).cities := '石嘴山市,吴忠市,固原市,中卫市';
  location_data.states('CN')(31).state_name := '新疆维吾尔自治区';
  location_data.states('CN')(31).state_short := '新';
  location_data.states('CN')(31).state_capital := '乌鲁木齐市';
  location_data.states('CN')(31).cities := '天山区,沙依巴克区,新市区,水磨沟区,头屯河区,达坂城区,米东区';
  location_data.states('CN')(32).state_name := '台湾省';
  location_data.states('CN')(32).state_short := '台';
  location_data.states('CN')(32).state_capital := '臺北市';
  location_data.states('CN')(32).cities := '高雄市,新北市,臺中市,桃園市,臺南市';
  location_data.states('CN')(33).state_name := '香港特别行政区';
  location_data.states('CN')(33).state_short := '港';
  location_data.states('CN')(33).state_capital := '中華人民共和國香港特別行政區';
  location_data.states('CN')(33).cities := '香港';
  location_data.states('CN')(34).state_name := '澳门特别行政区';
  location_data.states('CN')(34).state_short := '澳';
  location_data.states('CN')(34).state_capital := '中華人民共和國澳門特別行政區';
  location_data.states('CN')(34).cities := '濠鏡';

end location_data_cn;
/
