name: random_ninja-develop-push-action
on:
  push:
    branches:
      - develop

jobs:
  pre-env-setup:
    name: Initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  code-check:
    name: Code Check
    needs: [pre-env-setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  deploy-sql-to-oracle-test:
    name: RANDOM_NINJA Packages deployment - Test
    needs: [code-check]
    runs-on: ubuntu-latest
    env:
      TNS_ADMIN: /home/runner/work/random_ninja/random_ninja/deploy/Wallet_SGPoolTest
      ORACLOUD_UNAME: ${{ secrets.RANDOM_USER_NAME_TEST }}
      ORACLOUD_PWD: ${{ secrets.RANDOM_PASSWORD_TEST }}
    steps:
      - uses: actions/checkout@v2
      - name: Download instant client
        run: wget "https://download.oracle.com/otn_software/linux/instantclient/211000/instantclient-basic-linux.x64-21.1.0.0.0.zip"
      - name: Download sqlplus addition to instant client
        run: wget "https://download.oracle.com/otn_software/linux/instantclient/211000/instantclient-sqlplus-linux.x64-21.1.0.0.0.zip"
      - run: unzip instantclient-basic-linux.x64-21.1.0.0.0.zip
      - run: unzip instantclient-sqlplus-linux.x64-21.1.0.0.0.zip
      - run: sudo apt-get install libaio1
      - run: sudo sh -c "echo /home/runner/work/random_ninja/random_ninja/instantclient_21_1 > /etc/ld.so.conf.d/oracle-instantclient.conf"
      - run: sudo ldconfig
      - run: cp /home/runner/work/random_ninja/random_ninja/deploy/Wallet_SGPoolTest/* ./instantclient_21_1/network/admin/
      - run: ./instantclient_21_1/sqlplus "$ORACLOUD_UNAME"/"$ORACLOUD_PWD"@sgpooltest_low @/home/runner/work/random_ninja/random_ninja/deploy/deploy.sql